# Site settings
name: Lang Tuang
title: Lang Tuang - Software Engineer
description: Path to full stack developer 
url: https://tzerozo.github.io/
baseurl: ''
email: langktuang@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://tzerozo.github.io/resume.pdf
social:
  - title: email
    url: mailto:langktuang@gmail.com
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/tzerozo
  - title: linkedin
    url: https://www.linkedin.com/in/langtuang

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
